### ISSUE TITLE
Unable to start communication after accept the chat initialized by users.

### ISSUE THREAD

**Issue by praveens3190** [tompaana/intermediator-bot-sample#12]
For the logged in Agent , Accept or Reject Message is Shown , but once click on Accept.Communication was not start with user, and for user "Please wait for your request to be accepted" message is shown for user. Which method i needs to call after Click on Accept.

**Comment by garypretty** [comment]
I think this might be connected to #21. Ill close this for now. Please re-open if you are still experiencing issues.
