### ISSUE TITLE
Unable to call the Agent from the Bot

### ISSUE THREAD

**Issue by SamaraSara** [tompaana/intermediator-bot-sample#14]
Hello there and thanks for this project .
I have tested Scenario 1 (Channel to Channel ) and it worked successfully.
For Scenario 2, I have added the bot endpoint and the direct line key and I managed to install the npm, build and run the Agent UI . It runs on the http://localhost:8080 with a white screen having only Agent UI text in it. I can't seem to find where to make the request for the agents.
from the sender's side I send 'human' and no channels are aggregated so the request should be directed to the agent. How I am supposed to be calling the AgentController? or how does the bot call the Agent which uses the direct line?

**Comment by ronnelsantiago** [comment]
I'm having the same issue.. I can only see blank screen

**Comment by daltskin** [comment]
The agent UI polls the bot API endpoint eg:

setInterval(() =>
    fetch("http://803705b8.ngrok.io/api/agent/1")

So make sure you've updated the index.ts file within the agent codebase to your endpoint.

When it's working should look like this: https://

msdnshared.blob.core.windows.net/media/2017/08/Bot-HandOff2.gif

**Comment by SamaraSara** [comment]
I did that but cors is not enabled and the chat interface doesn't show.
I get a blank screen with this detected error:

No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.1.20:8080' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by daltskin** [comment]
You'll need to enable CORS.  In your webconfig.cs 
Register(....)
            config.EnableCors();

Agent controller already has attributes eg:

        [EnableCors("*", "*", "*")]
        public string GetAgentById(int id)

https://github.com/tompaana/intermediator-bot-sample/blob/master/IntermediatorBotSample/Controllers/AgentController.cs

**Comment by SamaraSara** [comment]
Yes. I have done so ... and now the Chat screen interface appears when a request to human assistance is made but after that the messages are not forwarded between them.

**Comment by daltskin** [comment]
What channel are you using to request the agent/human assistance?  Try using Slack.

Also, when everything is running - type "command reset" to clear down any routing state.

**Comment by carlosmorgado** [comment]
I have had the same problem exchanging messages between the Agent UI and Client asking for human assistance, the messages just seam to not go through.

**Comment by daltskin** [comment]
@SamaraSara, @carlosmorgado I've put a blog post together on how to set this up with a video sample for both scenarios.  Agent UI sample includes the setup required to get this up and running.  Hopefully this helps you both: [https://blogs.msdn.microsoft.com/jamiedalton/2017/08/10/microsoft-bot-framework-handing-off-to-a-human-for-agentssupervisors-with-c-and-the-botbuilder-sdk/](https://blogs.msdn.microsoft.com/jamiedalton/2017/08/10/microsoft-bot-framework-handing-off-to-a-human-for-agentssupervisors-with-c-and-the-botbuilder-sdk/) .  Let me know if this helps.

**Comment by carlosmorgado** [comment]
I followed everything you did and still can't trade messages between the Agent and the Client

**Comment by daltskin** [comment]
Are you receiving basic echo messages back from the bot ok as an end-user?

Assuming you've definitely modified the index.ts file with the Agent code (not the index.js), built then run?

If you put a breakpoint in the AgentController - it should get hit every 3 seconds or so (polling)

**Comment by daltskin** [comment]
@carlosmorgado, @SamaraSara any updates? or can I close this issue?

**Comment by tompaana** [comment]
Thank you @SamaraSara, @carlosmorgado and especially @daltskin! Closing this issue - reopen if the problem persists.
