### ISSUE TITLE
Move all strings to resource file(s)

### ISSUE THREAD

**Issue by tompaana** [tompaana/intermediator-bot-sample#20]
This would enable localization and is just a good practice.

**Comment by daltskin** [comment]
@garypretty - this should help.  You can test by changing the Emulator connection locale to Fr and then typing any old text to the bot - it will use the correct resources file automatically from the activity.locale

**Comment by garypretty** [comment]
Brilliant, thanks, will take a look.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tompaana** [comment]
Done in commit 8a41c97ccea5bc0e654d5de1d829a25c6dc431d9
