### ISSUE TITLE
Message routing fails for some channels

### ISSUE THREAD

**Issue by tompaana** [tompaana/intermediator-bot-sample#21]
Copied from https://github.com/tompaana/bot-message-routing/issues/1, reported by [Edward Bakker](https://github.com/edwardbakker)

"Message routing fails when using the combination of Messenger and Skype.
Example:
Messenger : Customer Service Agent
Skype: Customer

* In Messenger use "command add aggregation" to aggregate all request.
* In Skype request for User Handoff.
* Conversation between Service Agent and Customer is established
* Customer sends message which is received by the Service Agent
* Service Agent sends message which is NOT received by the Customer

When testing the above scenario with Messanger to Bot Emulator or Skype to Bot Emulator it all works fine..."

I believe this might already be fixed by @daltskin, but the fix needs to be verified.

**Comment by tompaana** [comment]
Actually I just realized this is the core project bug if any, but let's keep this here (too) until the fix is verified.

**Comment by miteshpatekar** [comment]
I am facing this issue connecting direct line to fb messenger. Connection is established and the user is able to send the message to agent, but agent's response is not received back.  Is it fixed ?

**Comment by tompaana** [comment]
Fixed in commit 49c7f08c10da4c6004ff4dad735ba18cc86972cd

Channels tested to work: (Emulator), Facebook, Skype, Slack and Teams.

**Comment by miteshpatekar** [comment]
Thank you @tompaana . I just tested with new version and 2-way communication works for FB messenger.
Great stuff !!

**Comment by tompaana** [comment]
Thanks for verifying! Was about time to get this fixed anyway.
