### ISSUE TITLE
Message routing fail if using Skype as Agent

### ISSUE THREAD

**Issue by dzeping96** [tompaana/intermediator-bot-sample#24]
Sorry for my English first..

Skype: Customer Agent
Bot Emulator: User

I found out that when I am using Skype as Agent, it unable to reply message to User, but I can receive message from User. If I am using other Channel other than Skype as Agent, it working fine. And also, I tried to use Bot Emulator as Agent and Skype as User, it is working fine too. I found out the problem is because of this part `messageRouterResult = await messageRouterManager.HandleActivityAsync(activity, false);`. If we using other Channel as Agent, it will reply OK as result, but if we using Skype as Agent, it will reply NoActionTaken as result. I just download this sample and tested without anything change, hope you can help me to solve this issues. Thanks a lot!

Here is some screenshot:-
**Agent on Skype**
![image](https://user-images.githubusercontent.com/23049317/32976495-e7b0722a-cc51-11e7-85c5-db03332004a5.png)

**User on Emulator**
![image](https://user-images.githubusercontent.com/23049317/32976499-073ee888-cc52-11e7-829d-9b3b4a83cf69.png)

**Comment by tompaana** [comment]
Thank you for reporting this and for the precise issue description! This is an obvious bug that needs to be fixed.

**Comment by daltskin** [comment]
Thought I'd fixed this a while back? https://github.com/tompaana/intermediator-bot-sample/commit/a19b34df7c0bfeedf6d0b4d357590b3c64bc8230

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tompaana** [comment]
@daltskin Unfortunately that fix broke the functionality for many other channels. I didn't just revert the changes, but added a special case in the code for Skype, but must've missed to test the case where Skype is the agent channel.

**Comment by daltskin** [comment]
Hmm. Does highlight the challenge around channel testing.   Labouriois without unit tests!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tompaana** [comment]
@daltskin Indeed.

**Comment by dzeping96** [comment]
@tompaana 
No problem. I will wait for your fix. Thank you so much!

**Comment by dzeping96** [comment]
Hi @tompaana,

FYI, I found out another problem, which after I publish the sample to **Azure App Service plan** with **Release** configuration, the Skype channel won't reply anything at all, it still working fine on any other channel. Is this related with the bug I mentioned in this topic? Thanks!

**Comment by daltskin** [comment]
There are some conditional #debug statements, could be related...

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dzeping96** [comment]
Hi @daltskin,

Thanks for your assisting, I just found out that Skype require some time to let the Channel online after switching endpoint. Thanks!

**Comment by tompaana** [comment]
Fixed in commit 49c7f08c10da4c6004ff4dad735ba18cc86972cd
