### ISSUE TITLE
Unable to cancel pending request in Skype

### ISSUE THREAD

**Issue by jmmcreynolds** [tompaana/intermediator-bot-sample#25]
I sent a request for human assistance from my Skype account to the bot, but no one was watching for requests and now Skype is stuck and I cannot issue any more requests for help from Skype. Every time I type "human" I get the following reply:

"Your request has already been receieved and we are waiting for an agent to respond"

How can I reset the session so that I can issue a request for human assistance again?

I already tried uncommenting the debug options so that I could try to run them from Skype, but none of them seemed to clear the stuck request.

**Comment by jmmcreynolds** [comment]
Looks like I missed uncommenting one of the debug commands. After running " /deleteprofile", followed by "command reset" the request is cleared and I can send another one.

**Comment by tompaana** [comment]
@jmmcreynolds No worries, thanks anyways :)
