### ISSUE TITLE
Need similar feature like Facebook chat window provide for different user chat by agent

### ISSUE THREAD

**Issue by sky5005e** [tompaana/intermediator-bot-sample#30]
Hello Tomi,

Thank you for your reply,
I have one more concern, it is possible to open new window for Agent Command Watch in webchat if new human assistant request comes from any user, and in the old window it will continued to chat with old user
I really appreciated.
Thanks

**Comment by tompaana** [comment]
Hi,

I don't think scenario 1 (channel to channel) should be made more complex **in this sample**. That said, scenario 2 needs some work - see issue #27 

Cheers,
Tomi
