### ISSUE TITLE
Azure table storage error

### ISSUE THREAD

**Issue by 20112077** [tompaana/intermediator-bot-sample#31]
I added the azure table connection string in the web.config file and now I get this error message:
[Error; ; ; [https://directline.botframework.com/; directline; {userid; Customer}; {JNChIJHE888G0mJ2PgfFa4; }]; Failed to add the pending request – this is likely an error caused by the storage implementation]

In the storage account there is a table created,  but there are no columns there.

**Comment by tompaana** [comment]
Silly question, but I need to be sure: Are you using the latest version in the master branch?

**Comment by 20112077** [comment]
I am using the latest version and the master branch

**Comment by tompaana** [comment]
There's not enough details here for me to know what's wrong. I suggest you remove the message routing nuget package and get the [Bot Message Routing project](https://github.com/tompaana/bot-message-routing) source code and reference it in the bot project directly. Then you can debug what's happening with the table storage implementation.

**Comment by 20112077** [comment]
I tried like you told me to do. A table is created, but then it fails at this function:

```
public static bool Insert<T>(CloudTable cloudTable, T entryToInsert) where T : TableEntity
        {
            TableOperation insertOperation = TableOperation.Insert(entryToInsert);
            TableResult insertResult = null;

            try
            {
                insertResult = cloudTable.Execute(insertOperation);
            }
            catch (Exception e)
            {
                System.Diagnostics.Debug.WriteLine($"Failed to insert the given entity into the table: {e.Message}");
                return false;
            }

            return (insertResult?.Result != null);
        }
```

Would it help when I send you the table connection string?

**Comment by tompaana** [comment]
I thank you for your trust, but please don't send me your connection string. The exception details might help though.

**Comment by 20112077** [comment]
This would be the visual studio output:
Using Azure Table Storage for the bot state
"iisexpress.exe" (CLR v4.0.30319: /LM/W3SVC/2/ROOT-1-131648023432320161): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll" geladen. PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
"iisexpress.exe" (CLR v4.0.30319: /LM/W3SVC/2/ROOT-1-131648023432320161): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\SMDiagnostics\v4.0_4.0.0.0__b77a5c561934e089\SMDiagnostics.dll" geladen. PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
Found a connection string - using AzureTableStorageRoutingDataManager
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
Failed to create the parties table (perhaps it already exists): Der Remoteserver hat einen Fehler zurückgegeben: (400) Ungültige Anforderung.
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
Failed to create the connections table (perhaps it already exists): Der Remoteserver hat einen Fehler zurückgegeben: (400) Ungültige Anforderung.
"iisexpress.exe" (CLR v4.0.30319: /LM/W3SVC/2/ROOT-1-131648023432320161): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Security\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Security.dll" geladen. PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
"iisexpress.exe" (CLR v4.0.30319: /LM/W3SVC/2/ROOT-1-131648023432320161): "C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Transactions\v4.0_4.0.0.0__b77a5c561934e089\System.Transactions.dll" geladen. PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
"iisexpress.exe" (CLR v4.0.30319: /LM/W3SVC/2/ROOT-1-131648023432320161): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Workflow.Runtime\v4.0_4.0.0.0__31bf3856ad364e35\System.Workflow.Runtime.dll" geladen. PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
"iisexpress.exe" (CLR v4.0.30319: /LM/W3SVC/2/ROOT-1-131648023432320161): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Workflow.ComponentModel\v4.0_4.0.0.0__31bf3856ad364e35\System.Workflow.ComponentModel.dll" geladen. PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
"iisexpress.exe" (CLR v4.0.30319: /LM/W3SVC/2/ROOT-1-131648023432320161): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Workflow.Activities\v4.0_4.0.0.0__31bf3856ad364e35\System.Workflow.Activities.dll" geladen. PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
"iisexpress.exe" (CLR v4.0.30319: /LM/W3SVC/2/ROOT-1-131648023432320161): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll" geladen. PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
"iisexpress.exe" (CLR v4.0.30319: /LM/W3SVC/2/ROOT-1-131648023432320161): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Internals\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Internals.dll" geladen. PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
"iisexpress.exe" (CLR v4.0.30319: /LM/W3SVC/2/ROOT-1-131648023432320161): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Build.Framework\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.Build.Framework.dll" geladen. PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
"iisexpress.exe" (CLR v4.0.30319: /LM/W3SVC/2/ROOT-1-131648023432320161): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.DurableInstancing\v4.0_4.0.0.0__31bf3856ad364e35\System.Runtime.DurableInstancing.dll" geladen. PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
"iisexpress.exe" (CLR v4.0.30319: /LM/W3SVC/2/ROOT-1-131648023432320161): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml.ReaderWriter\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Xml.ReaderWriter.dll" geladen. PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
"iisexpress.exe" (CLR v4.0.30319: /LM/W3SVC/2/ROOT-1-131648023432320161): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.IO\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.IO.dll" geladen. PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
"iisexpress.exe" (CLR v4.0.30319: /LM/W3SVC/2/ROOT-1-131648023432320161): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Data.SqlXml\v4.0_4.0.0.0__b77a5c561934e089\System.Data.SqlXml.dll" geladen. PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
"iisexpress.exe" (CLR v4.0.30319: /LM/W3SVC/2/ROOT-1-131648023432320161): "C:\WINDOWS\Microsoft.Net\assembly\GAC_32\Microsoft.VisualBasic.Activities.Compiler\v4.0_10.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualBasic.Activities.Compiler.dll" geladen. PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
"iisexpress.exe" (CLR v4.0.30319: /LM/W3SVC/2/ROOT-1-131648023432320161): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml.Hosting\v4.0_4.0.0.0__31bf3856ad364e35\System.Xaml.Hosting.dll" geladen. PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
Ausnahme ausgelöst: "System.Reflection.ReflectionTypeLoadException" in mscorlib.dll
"iisexpress.exe" (CLR v4.0.30319: /LM/W3SVC/2/ROOT-1-131648023432320161): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Collections\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Collections.dll" geladen. PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
"iisexpress.exe" (CLR v4.0.30319: /LM/W3SVC/2/ROOT-1-131648023432320161): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Data.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Data.Linq.dll" geladen. PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
"iisexpress.exe" (CLR v4.0.30319: /LM/W3SVC/2/ROOT-1-131648023432320161): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Threading.Tasks\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Threading.Tasks.dll" geladen. PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
"iisexpress.exe" (CLR v4.0.30319: /LM/W3SVC/2/ROOT-1-131648023432320161): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Text.Encoding\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Text.Encoding.dll" geladen. PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
"iisexpress.exe" (CLR v4.0.30319: /LM/W3SVC/2/ROOT-1-131648023432320161): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Globalization\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Globalization.dll" geladen. PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
"iisexpress.exe" (CLR v4.0.30319: /LM/W3SVC/2/ROOT-1-131648023432320161): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_de_b77a5c561934e089\mscorlib.resources.dll" geladen. Das Modul wurde ohne Symbole erstellt.
"iisexpress.exe" (CLR v4.0.30319: /LM/W3SVC/2/ROOT-1-131648023432320161): "Anonymously Hosted DynamicMethods Assembly" geladen. 
"iisexpress.exe" (CLR v4.0.30319: /LM/W3SVC/2/ROOT-1-131648023432320161): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http.WebRequest\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.WebRequest.dll" geladen. PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
Failed to find a setting value by key "RejectConnectionRequestIfNoAggregationChannel"
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
Failed to retrieve the bot parties: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
Failed to insert the given entity into the table: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
Failed to retrieve the bot parties: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
Failed to retrieve the user parties: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
Failed to insert the given entity into the table: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
Failed to retrieve the bot parties: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
Failed to insert the given entity into the table: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
Failed to retrieve the bot parties: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
Failed to retrieve the user parties: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
Failed to insert the given entity into the table: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
Failed to retrieve the connected parties: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
Failed to retrieve the connected parties: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "System.Net.WebException" in Microsoft.WindowsAzure.Storage.dll
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in mscorlib.dll
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "System.Net.WebException" in System.dll
Ausnahme ausgelöst: "System.Web.HttpException" in Microsoft.Bot.Builder.Azure.dll
Ausnahme ausgelöst: "System.Net.WebException" in Microsoft.WindowsAzure.Storage.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
Ausnahme ausgelöst: "System.Net.WebException" in Microsoft.WindowsAzure.Storage.dll
Ausnahme ausgelöst: "System.Web.HttpException" in mscorlib.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in Microsoft.WindowsAzure.Storage.dll
Ausnahme ausgelöst: "System.Web.HttpException" in mscorlib.dll
Ausnahme ausgelöst: "System.Web.HttpException" in mscorlib.dll
Ausnahme ausgelöst: "System.Web.HttpException" in mscorlib.dll
Ausnahme ausgelöst: "System.Web.HttpException" in mscorlib.dll
Ausnahme ausgelöst: "System.Web.HttpException" in mscorlib.dll
Ausnahme ausgelöst: "System.Web.HttpException" in mscorlib.dll
"iisexpress.exe" (CLR v4.0.30319: /LM/W3SVC/2/ROOT-1-131648023432320161): "C:\Users\Spoecker\AppData\Local\Temp\Temporary ASP.NET Files\vs\661f4b21\c0506690\assembly\dl3\594f67fd\00206ba0_07acd301\Microsoft.Bot.Builder.resources.dll" geladen. Das Modul wurde ohne Symbole erstellt.
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in mscorlib.dll
Ausnahme ausgelöst: "System.Web.HttpException" in Microsoft.Bot.Builder.Azure.dll
Ausnahme ausgelöst: "System.Web.HttpException" in mscorlib.dll
Ausnahme ausgelöst: "Microsoft.WindowsAzure.Storage.StorageException" in mscorlib.dll
Ausnahme ausgelöst: "System.Web.HttpException" in Microsoft.Bot.Builder.Azure.dll
Ausnahme ausgelöst: "System.Web.HttpException" in mscorlib.dll
Ausnahme ausgelöst: "System.Web.HttpException" in Microsoft.Bot.Builder.dll
Ausnahme ausgelöst: "System.Web.HttpException" in mscorlib.dll
Ausnahme ausgelöst: "System.Web.HttpException" in mscorlib.dll
Ausnahme ausgelöst: "System.Web.HttpException" in mscorlib.dll
Ausnahme ausgelöst: "System.Web.HttpException" in mscorlib.dll
Ausnahme ausgelöst: "System.Web.HttpException" in mscorlib.dll
Ausnahme ausgelöst: "System.Web.HttpException" in mscorlib.dll
Ausnahme ausgelöst: "System.Web.HttpException" in mscorlib.dll
Ausnahme ausgelöst: "System.Web.HttpException" in System.Web.Http.dll
Ausnahme ausgelöst: "System.Web.HttpException" in mscorlib.dll
Ausnahme ausgelöst: "System.Web.HttpException" in mscorlib.dll
Ausnahme ausgelöst: "System.Web.HttpException" in mscorlib.dll

**Comment by 20112077** [comment]
Today I tried again with a fresh download and I got it working. I restored and updated the Nuget packages the last time I tried. But when you update the NuGet packages it stops working for me.

**Comment by tompaana** [comment]
Good to hear! (Especially since I'm quite busy :)) I'll close the issue. Reopen if the problem reappears.

**Comment by 20112077** [comment]
Will the sample be updated with the newest NuGet Packages at some point?

**Comment by tompaana** [comment]
As soon as possible given that I don't forget. Really busy now, sorry!
