### ISSUE TITLE
Application settings and credentials

### ISSUE THREAD

**Issue by zexzex** [tompaana/intermediator-bot-sample#36]
I published a bot. But stumbled with a problem.
   <add key = "RoutingDataStorageConnectionString" value = "" />
If I leave connection string empty, then the bot is working, but it can not accept the "@intermediatorbot accept default-user" , I get an error "Request to 'https://bot.azurewebsites.net/api/messages' failed: [500] Internal Server Error".
if I fill <add key = "RoutingDataStorageConnectionString" value = "DefaultEndpointsProtocol=https;AccountName=bot;AccountKey=2WibfbxreEGTH5rxUHo88nWK59dNfO4vptMnH4Hhdhelwekle5ziCKTo0/mYis+GfRjk5lsZHZcVyD6GcWw==;EndpointSuffix=core.windows.net" />. bot does not work and immediately gives "Request to 'https://bot.azurewebsites.net/api/messages' failed: [500] Internal Server Error".
Tried using key 1 and key 2

**Comment by tompaana** [comment]
Closing as this is no longer relevant, since the project has been migrated to Bot Framework v4.
