### ISSUE TITLE
Replacing RootDialog, PromptDialog.Choice CallBack Never called

### ISSUE THREAD

**Issue by piriej** [tompaana/intermediator-bot-sample#38]
Whilst experimenting with this sample, I attempted to replace the root dialog with the following (Which works in other projects). Can someone elaborate why this simple PromptDialog.Choice doesn't work in this solution? Much appreciated.

`using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.Bot.Builder.Dialogs;
using Microsoft.Bot.Connector;

namespace IntermediatorBot.Dialogs
{
    /// <summary>
    /// Simple dialog that will only ever provide simple instructions.
    /// </summary>
    [Serializable]
    public class RootDialog : IDialog<object>
    {
        private IEnumerable<string> Descriptions(Type type) => Enum.GetNames(type).Select(value => Regex.Replace(value, "([a-z])([A-Z])", "$1 $2"));
        private string Description(Type type, object value) => Regex.Replace(Enum.GetName(type, value), "([a-z])([A-Z])", "$1 $2");
        public string TimeOfDay => DateTime.Now.Hour < 12 ? "morning" : DateTime.Now.Hour < 17 ? "afternoon" : "evening";

        public Task StartAsync(IDialogContext context)
        {
            context.Wait(MessageReceivedAsync);
            return Task.CompletedTask;
        }

        private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> result)
        {
            var greeting = string.Format("Good {0}", TimeOfDay);
            await context.PostAsync(greeting);
            PromptDialog.Choice(
                context: context,
                resume: IsTenancyRelatedAsync,
                options: ((IEnumerable<ServiceOfferingOptions>)Enum.GetValues(typeof(ServiceOfferingOptions))),
                descriptions: Descriptions(typeof(ServiceOfferingOptions)),
                prompt: "Please select from:",
                retry: "Ooops",
                attempts: 3,
                promptStyle: PromptStyle.Auto
            );
        }

        private async Task IsTenancyRelatedAsync(IDialogContext context, IAwaitable<ServiceOfferingOptions> result)
        {
            var confirm = await result;

            if (confirm == ServiceOfferingOptions.OptionA)
            {
                await context.PostAsync("OptionA enquiry.");
                context.Done<object>(null);
            }
            else
            {
                await context.PostAsync("Some other enquiry.");
                context.Done<object>(null);
            }
        }

        private async Task CloseConversation(IDialogContext context, IAwaitable<object> result)
        {
            await context.PostAsync("Thanks, Goodbye.");
            context.Done<object>(null);
        }

        public enum ServiceOfferingOptions
        {
            OptionA,
            OptionB,
            SomeOtherOption
        }
    }
}
`

**Comment by tompaana** [comment]
Deprecated. No more dialogs in v4.
