### ISSUE TITLE
Add timestamps to Party class

### ISSUE THREAD

**Issue by tompaana** [tompaana/intermediator-bot-sample#5]
It might be useful to know the times of different events, for example, how long a person has been waiting for his/her request to be approved.

**Comment by garypretty** [comment]
I have a few ideas to utilise these timestamps so keep me updated when you add them :)

**Comment by tompaana** [comment]
Implemented in https://github.com/tompaana/bot-message-routing/commit/a0f19f04c9520bb623e29d45f6fe9b5ddc2dab1e

Not tested yet though.
