### ISSUE TITLE
Skips OnStart

### ISSUE THREAD

**Issue by nouranmosallam** [tompaana/intermediator-bot-sample#52]
Whenever the handoff middleware is added to the virtual assistant the bot doesn’t enter the OnStart of the MainDialog. Any idea how to fix that ?

**Comment by mailforsachin** [comment]
Let me know if you get some lead on this. I have been unsuccessful to get this integrated with the VA /EBT code.

**Comment by nouranmosallam** [comment]
Yes, you'll have to add this line  await next(ct).ConfigureAwait(false);  two places in the OnTurnAsync of the HandoffMiddleware.cs.

` public async Task OnTurnAsync(ITurnContext context, NextDelegate next, CancellationToken ct)
        {
            Activity activity = context.Activity;

            if (activity.Type is ActivityTypes.Message)
            {
                bool.TryParse(
                    Configuration[KeyRejectConnectionRequestIfNoAggregationChannel],
                    out bool rejectConnectionRequestIfNoAggregationChannel);

                // Store the conversation references (identities of the sender and the recipient [bot])
                // in the activity
                MessageRouter.StoreConversationReferences(activity);

                AbstractMessageRouterResult messageRouterResult = null;

                // Check the activity for commands
                if (await CommandHandler.HandleCommandAsync(context) == false)
                {
                    // No command detected/handled

                    // Let the message router route the activity, if the sender is connected with
                    // another user/bot
                    messageRouterResult = await MessageRouter.RouteMessageIfSenderIsConnectedAsync(activity);

                    if (messageRouterResult is MessageRoutingResult
                        && (messageRouterResult as MessageRoutingResult).Type == MessageRoutingResultType.NoActionTaken)
                    {
                        // No action was taken by the message router. This means that the user
                        // is not connected (in a 1:1 conversation) with a human
                        // (e.g. customer service agent) yet.

                        // Check for cry for help (agent assistance)
                        if (!string.IsNullOrWhiteSpace(activity.Text)
                            && activity.Text.ToLower().Contains("human"))
                        {
                            // Create a connection request on behalf of the sender
                            // Note that the returned result must be handled
                            messageRouterResult = MessageRouter.CreateConnectionRequest(
                                MessageRouter.CreateSenderConversationReference(activity),
                                rejectConnectionRequestIfNoAggregationChannel);
                        }
                        else
                        {
                            // No action taken - this middleware did not consume the activity so let it propagate
                            await next(ct).ConfigureAwait(false); //First Place
                        }
                    }
                }

                // Uncomment to see the result in a reply (may be useful for debugging)
                //if (messageRouterResult != null)
                //{
                //    await MessageRouter.ReplyToActivityAsync(activity, messageRouterResult.ToString());
                //}

                // Handle the result, if necessary
                await MessageRouterResultHandler.HandleResultAsync(messageRouterResult);
            }
            else
            {
                await next(ct).ConfigureAwait(false); //Second Place
            }
        }`

**Comment by mailforsachin** [comment]
@nouranmosallam Is it possible for you to upload the solution somewhere? Intermediator bot sample works fine for me as an independent solution but when I add this to the VA template, it doesnt even build. I have been running around for several weeks now. Would appreciate if you can help me here in any context

**Comment by nouranmosallam** [comment]
> @nouranmosallam Is it possible for you to upload the solution somewhere? Intermediator bot sample works fine for me as an independent solution but when I add this to the VA template, it doesnt even build. I have been running around for several weeks now. Would appreciate if you can help me here in any context

Okay I uploaded the code for your here "https://github.com/nouranmosallam/HandoffInMicrosftVirtualAssitant" you might still need to edit some stuff concerning the VA itself but this should give you at least the idea of how to integrate it.
