### ISSUE TITLE
Exception: "Operation returned an invalid status code 'badrequest'" is returned when Agent types @Bot GetRequests to get the pending accepted requests from Teams channel.

### ISSUE THREAD

**Issue by praneethkolla** [tompaana/intermediator-bot-sample#53]
Hi @tompaana , can you please take a look into this issue:

1. **This issue is observed when the solution is published in Teams channel only**. (The above issue is not observed in emulator)

2. When Agent typed '@Bot GetRequests' command, agent is not able to get the pending accepted request (request which is accepted by the Agent during the time of conversation with first user) from the second user.

**Comment by kanazaca** [comment]
@praneethkolla I think the problem is in this [Line](https://github.com/tompaana/intermediator-bot-sample/blob/96f8af7b427294a76bfdf7d94e9154db3401760e/IntermediatorBotSample/CommandHandling/CommandHandler.cs#L173)

If you want to go past this issue, just comment it.

**Comment by praneethkolla** [comment]
Thank-you @kanazaca , this solved my issue now.
