### ISSUE TITLE
TRANSFER THE CONVERSATION FROM BOT TO THE AGENT

### ISSUE THREAD

**Issue by sayyednazeer** [tompaana/intermediator-bot-sample#9]
@tompaana i am using .NET SDK

How can i transfer the conversation which i have done with bot to the agent when i get connected with agent.

**Comment by tompaana** [comment]
I'm afraid I fail to understand the issue. Could you please elaborate a bit? Are there some problems in the steps described in the README?

**Comment by garypretty** [comment]
Closing this for now. @sayyednazeer feel free to re-open if you have not resolved the issue.
